import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { ClientProviders } from "@/lib/providers/ClientProviders";

// for non layouts shifts font loading
// fonts load once, applied to the entire app
// available before first paint
// create a variable and pass it torectly to className or can be passed to tailwinf utilities
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // variables will become available to wntire app
        // css variables cascade
        // everything inside body can access them
      >
        <ClientProviders>
          <Toaster
            position="top-center"
            reverseOrder={false}
            gutter={8}
            containerClassName=""
            containerStyle={{}}
            toasterId="default"
          />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
