name: Hello bro

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building..."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running step..."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying step"
  
   
