name: Test variables

on:
  push:
    branches:
      - staging
      - workflow
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  display_variables:
    # runs-on: ubuntu-latest
    if: ${{ vars.JOB_TYPE == 'build' }}
    runs-on: ${{ vars.RUNNER_UBUNTU }}
    # environment: ${{vars.GITHUB_REPOSITORY}}
    steps:
      - name: Use variables
        run: |
          echo "My name: $env:MY_NAME"
          echo "Job Type: $env:JOB_TYPE"
