name: Build, Test and Deploy to Vercel

on:
  push:
    branches: [ workflow, staging, master ]

  pull_request:
    types: [ opened, reopened, closed ]
    branches: [ staging, master ]

jobs:
  install:
    runs-on: ubuntu-latest #type of machine to run the job on.

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 #cloning the repo

      - name: Setup Node
        uses: actions/setup-node@v4 #installing node
        with:
          #additional node settings
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci --legacy-peer-deps

  component-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          component: true

  e2e-tests:
    runs-on: ubuntu-latest
    needs: component-tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          browser: chrome

  build:
    runs-on: ubuntu-latest
    needs: e2e-tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .next

      - name: Deploy
        run: echo "Deploy now"
